services:
  app:
    image: 'ticket-ordering-service-image'
    container_name: kpo-ticket-ordering-service
    expose:
      - '8081'
    ports:
      - '8081:8081'
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://db:5432/KPO-TICKET-DB
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=KPO-TICKET-DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password